Repository ridisi95/gulag, pull requests merged in 2021-01, with the labels that each got.

#1 Change version of maven-compiler-plugin on version of project.
  pom.xml
Labels: good first issue, invalid

#4 Add Basic Auth.
  pom.xml
  sql/user-data.sql
  src/main/java/com/gulag/config/SecurityConfig.java
  src/main/java/com/gulag/entity/Role.java
  src/main/java/com/gulag/entity/UserEntity.java
  src/main/java/com/gulag/repos/UsersRepository.java
  src/main/java/com/gulag/services/AuthUserService.java
Labels: enhancement

#8 Add table to DB tournament_registration.
  pom.xml
  src/main/java/com/gulag/config/SecurityConfig.java
  src/main/java/com/gulag/controller/PlayerController.java
  src/main/java/com/gulag/controller/TourRegController.java
  src/main/java/com/gulag/dto/TourRegDTO.java
  src/main/java/com/gulag/dto/UserDTO.java
  src/main/java/com/gulag/entity/PlayerEntity.java
  src/main/java/com/gulag/entity/TourRegEntity.java
  src/main/java/com/gulag/entity/TournamentEntity.java
  src/main/java/com/gulag/entity/UserEntity.java
  src/main/java/com/gulag/mapper/TourRegDTOMapper.java
  src/main/java/com/gulag/mapper/UserEntityDTOMapper.java
  src/main/java/com/gulag/relationship/TourRegRelationId.java
  src/main/java/com/gulag/repos/TourRegRepository.java
  src/main/java/com/gulag/repos/UsersRepository.java
  src/main/java/com/gulag/services/AuthUserService.java
  src/main/java/com/gulag/services/TourRegService.java
  src/main/java/com/gulag/services/UserService.java
  src/main/java/com/gulag/services/impl/TourRegServiceImpl.java
  src/main/java/com/gulag/services/impl/UserServiceImpl.java
  src/main/resources/migrations/V3__T14.sql
Labels: enhancement

#11 GULAG-T-18: setup storybook
  front-end/.storybook/main.js
  front-end/.storybook/preview.js
  front-end/package.json
Labels: front-end

#12 Feature/GULAG-T-17 ADD: styles thema
  front-end/models/store/actions/index.ts
  front-end/models/store/index.ts
  front-end/models/theme/index.ts
  front-end/models/theme/styled.d.ts
  front-end/next.config.js
  front-end/package.json
  front-end/pages/_app.tsx
  front-end/pages/_document.tsx
  front-end/pages/index.tsx
  front-end/src/config/styles/indext.tsx
  front-end/src/config/theme/colors/index.ts
  front-end/src/config/theme/fonts/index.ts
  front-end/src/config/theme/index.ts
  front-end/src/config/theme/transition/index.ts
  front-end/src/store/index.ts
  front-end/src/store/reducers/authentication/index.ts
  front-end/tsconfig.json
  front-end/yarn.lock
Labels: front-end

#14 T-21. Added Dockerfile for fast start project.
  Dockerfile
  docker-compose.yml
Labels: enhancement
